---
kind: pkgfile.Build
spec:
  targets:
    - sbc-rockchip
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - TOOLS_PREFIX
    - TOOLS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.12.0
      - name: TOOLS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: TOOLS
        defaultValue: v1.12.0
---
kind: common.Build
spec:
  ignoredPaths:
    - go.work.sum
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - ARM-software/arm-trusted-firmware
      versioning: 'regex:^((?<compatibility>\S+)-)?v(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
      allowedVersions: "< 6.19"
    - matchPackageNames:
        - u-boot/u-boot
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)(?<prerelease>-rc\d+)?$'
